[package]
name = "haoyong-error-report"
version = "0.1.0"
edition = "2021"

[dependencies]
miette = { version = "7.2.0", default-features = false }
poem-openapi = { version = "5.0.3", default-features = false }
